### ISSUE TITLE
New domain name

### ISSUE THREAD

**Issue by clharman** [UM-ESG/esg#71]
I emailed Kyle re: who assigns the domain names.  Once we get our new one we can switch.

**Comment by nickbabcock** [comment]
Hostmaster took care of it.

output of `dig umec.engin.umich.edu`

    umec.engin.umich.edu.   1800    IN      CNAME   esg.engin.umich.edu.
    esg.engin.umich.edu.    1800    IN      A       192.241.253.241

**Comment by nickbabcock** [comment]
In case any are interested, I have all `umec` requests automatically redirecting to `esg` requests. So no URLs are broken :tada:
