### ISSUE TITLE
Committees

### ISSUE THREAD

**Issue by nickbabcock** [UM-ESG/esg#74]
Since the committees are described in the new ESG bylaws, what is the use of having a separate committee section to the website? We have to overhaul this section as well to get rid of the old information about committees.

**Comment by rpolik** [comment]
I think it would be advantageous to still have committee descriptions outside of the bylaws as we are still recruiting members from the general student body and the information should be easily accessible.  I can rewrite the descriptions later tonight.

**Comment by rpolik** [comment]
Finished with #80
