### ISSUE TITLE
New By-laws and Constitution

### ISSUE THREAD

**Issue by nickbabcock** [UM-ESG/esg#75]
What's the plan for making the constitution and by-laws available to the public? The old information was converted to markdown, but the new information is hosted in google docs (at least the by-laws are)

**Comment by clharman** [comment]
I believe we decided to link to pdfs... @rpolik do you remember?

**Comment by rpolik** [comment]
I don't remember, but I agree that linking to pdfs would be best.  In the past we have linked to google docs because we don't want to host pdfs.  I think hosting pdfs looks cleaner but I also have no idea how to do it.

**Comment by clharman** [comment]
You mean hosting on the website?  In some instances I think we have linked
to a pdf that is hosted on google drive, which I think is ideal.

On Sat, Jan 3, 2015 at 9:36 PM, Robert Polik <notifications@github.com>
wrote:

> I don't remember, but I agree that linking to pdfs would be best. In the
> past we have linked to google docs because we don't want to host pdfs. I
> think hosting pdfs looks cleaner but I also have no idea how to do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UM-ESG/esg/issues/75#issuecomment-68618352>.
>



-- 
Colin Luongo Harman
UM Engineering Council, Director of Administration
Mechanical Engineering, 2015

**Comment by rpolik** [comment]
Yes, I mean hosting on the website, I don't like dealing with google drive's pdf reader when I am looking at a website, but that is just personal preference.  It is much easier to link to google drive (and it makes changing files much easier), so doing that is fine.  We might want to make a folder in the drive just for things posted on the website to keep the drive from becoming cluttered.

**Comment by rpolik** [comment]
This still needs to be done, we can just link to the google docs in the ESG drive.  My computer does not work, so I can't fix it now, if one of you guys can, great; if not, I should be able to do it tomorrow or Wednesday.

**Comment by nickbabcock** [comment]
Based on the recent work from @balghane, is this done?

**Comment by rpolik** [comment]
Yes

**Comment by balghane** [comment]
What I did was a short-term solution. The drive could be more organized, and I still think it would be nice to have plain-text on the website, but at least we have the up-to-date bylaws and constitution on the website.
