### ISSUE TITLE
Add Location to Office Hours Information

### ISSUE THREAD

**Issue by eazellou** [UM-ESG/esg#94]
Where are your office hours? No one knows because that information isn't listed anywhere obvious.

**Comment by nickbabcock** [comment]
They should be in the EECS Bullpen (1226 EECS). It's a collection of cubicles right next to the DB cafe and the computer lab. The ESG office is farthest office straight-back. But yes, you are right, the "where" information should be in the calendar. 

@clharman, who can do that? The calendar at http://esg.engin.umich.edu/executive-board.html says "UMEC Office Hours" and is blank. Please remove or add in the office hours.

**Comment by rpolik** [comment]
I updated the google calendar on the main page to list the location of the office hours.  @eazellou If you think there is a better location for this information (i.e. where you first went to look for it), let us know.

**Comment by eazellou** [comment]
That's perfect!  The details in the calendar were the first place we looked during our board meeting today.  :)

**Comment by eazellou** [comment]
Shoot, shouldn't have closed it because the calendar on the executive board page is still empty.  The one on the main page is great, though.  I think it would make sense to just have that main calendar be the one on the executive board instead of having two, this way you'd only have to deal with keeping one up to date.

**Comment by nickbabcock** [comment]
I removed the empty calendar in accc1b4
